bf-upgrade.env/bmc: Support Golden Images in PLDM format
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/src/bf-upgrade.env/bmc b/src/bf-upgrade.env/bmc
--- a/src/bf-upgrade.env/bmc
+++ b/src/bf-upgrade.env/bmc
@@ -26,6 +26,9 @@ CEC_MIN_RESET_VERSION="00.02.0180.0000"
 UPDATE_DPU_GOLDEN_IMAGE=${UPDATE_DPU_GOLDEN_IMAGE:-"yes"}
 UPDATE_NIC_FW_GOLDEN_IMAGE=${UPDATE_NIC_FW_GOLDEN_IMAGE:-"yes"}
 RESET_BMC_RSHIM_LOG=${RESET_BMC_RSHIM_LOG:-"yes"}
+# The PLDM format UUID in hexadecimal (no dashes, little-endian order).
+PLDM_UUID="f018878ccb7d49439800a02f059aca02"
+
 bmc_pref=""
 if (lspci -n -d 15b3: | grep -wq 'a2dc'); then
         bmc_pref="bf3"
@@ -349,6 +352,30 @@ wait_bmc_task_complete()
 	/bin/rm -f $output
 }
 
+get_bmc_firmware_version()
+{
+	get_bmc_token
+	BMC_FIRMWARE_URL=$(curl -sSk -H "X-Auth-Token: $BMC_TOKEN" -X GET https://${BMC_IP}/redfish/v1/UpdateService/FirmwareInventory | grep BMC_Firmware | awk '{print $NF}' | tr -d \")
+	ilog "- INFO: BMC_FIRMWARE_URL: $BMC_FIRMWARE_URL"
+	BMC_INSTALLED_VERSION="$(curl -sSk -H "X-Auth-Token: $BMC_TOKEN" -X GET https://${BMC_IP}${BMC_FIRMWARE_URL} | jq -r ' .Version' | grep -o "\([0-9]\+\).\([0-9]\+\)-\([0-9]\+\)")"
+	if [ -z "$BMC_INSTALLED_VERSION" ]; then
+		ilog "- ERROR: Cannot detect running BMC firmware version"
+		RC=$((RC+1))
+		return 1
+	fi
+	ilog "Running BMC firmware version: $BMC_INSTALLED_VERSION"
+}
+
+is_pldm_file()
+{
+	# Read the first 16 bytes and print as hex
+	file_uuid=$(xxd -p -l 16 "$1")
+	if [ "$file_uuid" == "$PLDM_UUID" ]; then
+		return 0
+	fi
+	return 1
+}
+
 update_bmc_fw()
 {
 	rc=0
@@ -379,17 +406,9 @@ update_bmc_fw()
 	fi
 	ilog "Provided BMC firmware version: $BMC_IMAGE_VERSION"
 
-	get_bmc_token
-
-	BMC_FIRMWARE_URL=$(curl -sSk -H "X-Auth-Token: $BMC_TOKEN" -X GET https://${BMC_IP}/redfish/v1/UpdateService/FirmwareInventory | grep BMC_Firmware | awk '{print $NF}' | tr -d \")
-	ilog "- INFO: BMC_FIRMWARE_URL: $BMC_FIRMWARE_URL"
-	BMC_INSTALLED_VERSION="$(curl -sSk -H "X-Auth-Token: $BMC_TOKEN" -X GET https://${BMC_IP}${BMC_FIRMWARE_URL} | jq -r ' .Version' | grep -o "\([0-9]\+\).\([0-9]\+\)-\([0-9]\+\)")"
 	if [ -z "$BMC_INSTALLED_VERSION" ]; then
-		ilog "- ERROR: Cannot detect running BMC firmware version"
-		RC=$((RC+1))
-		return 1
+		get_bmc_firmware_version
 	fi
-	ilog "Running BMC firmware version: $BMC_INSTALLED_VERSION"
 
 	if [ "${BMC_IMAGE_VERSION}" == "${BMC_INSTALLED_VERSION}" ]; then
 		if [ "X${FORCE_BMC_FW_INSTALL}" == "Xyes" ]; then
@@ -414,9 +433,11 @@ update_bmc_fw()
 	BMC_FIRMWARE_UPDATED="yes"
 
 	wait_bmc_task_complete
+	post_bmc_install_message="INFO: BMC firmware was updated to: ${BMC_IMAGE_VERSION}"
 	if [ "$BMC_REBOOT" != "yes" ]; then
-		log "INFO: BMC firmware was updated to: ${BMC_IMAGE_VERSION}. BMC restart is required."
+		post_bmc_install_message="${post_bmc_install_message}. BMC restart is required"
 	fi
+	log "${post_bmc_install_message}"
 	if [ "$BMC_UPGRADE_RESET" == "yes" ]; then
 		BMC_UPGRADE_RESET=1 bfcfg -f /dev/null
 	fi
@@ -475,18 +496,8 @@ update_cec_fw()
 
 	ilog "Proceeding with the CEC firmware update..."
 
-	if [ -z "$BMC_FIRMWARE_URL" ]; then
-		BMC_FIRMWARE_URL=$(curl -sSk -H "X-Auth-Token: $BMC_TOKEN" -X GET https://${BMC_IP}/redfish/v1/UpdateService/FirmwareInventory | grep BMC_Firmware | awk '{print $NF}' | tr -d \")
-		ilog "- INFO: BMC_FIRMWARE_URL: $BMC_FIRMWARE_URL"
-	fi
-
 	if [ -z "$BMC_INSTALLED_VERSION" ]; then
-		BMC_INSTALLED_VERSION="$(curl -sSk -H "X-Auth-Token: $BMC_TOKEN" -X GET https://${BMC_IP}${BMC_FIRMWARE_URL} | jq -r ' .Version' | grep -o "\([0-9]\+\).\([0-9]\+\)-\([0-9]\+\)")"
-		if [ -z "$BMC_INSTALLED_VERSION" ]; then
-			ilog "- ERROR: Cannot detect running BMC firmware version"
-			RC=$((RC+1))
-			return 1
-		fi
+		get_bmc_firmware_version
 	fi
 
 	if [[ $(echo -e "${BMC_MIN_MULTIPART_VERSION}\n${BMC_INSTALLED_VERSION}" | sort -V | head -n1) == "${BMC_MIN_MULTIPART_VERSION}" ]]; then
@@ -541,6 +552,7 @@ bmc_reboot_from_dpu()
 update_dpu_golden_image()
 {
 	rc=0
+	image_type=""
 	log "Updating DPU Golden Image"
 	image=${DPU_GOLDEN_IMAGE}
 
@@ -550,37 +562,89 @@ update_dpu_golden_image()
 		return 1
 	fi
 
-	prepare_sshpass_environment
-
-	ilog "Found DPU Golden Image: $image"
-	DPU_GI_IMAGE_VERSION="$(sha256sum $image | awk '{print $1}')"
-	ilog "Provided DPU Golden Image version: $DPU_GI_IMAGE_VERSION"
-
-	DPU_GI_INSTALLED_VERSION="$(sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} dpu_golden_image golden_image_arm -V 2> /dev/null)"
-	ilog "Installed DPU Golden Image version: $DPU_GI_INSTALLED_VERSION"
-
-	if [ "$DPU_GI_IMAGE_VERSION" == "$DPU_GI_INSTALLED_VERSION" ]; then
-		ilog "Installed DPU Golden Image version is the same as provided. Skipping DPU Golden Image update."
+	if is_pldm_file $image; then
+		image_type="pldm"
 	else
-		sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} mkdir -p ${BMC_TMP_DIR}/golden-image-arm
-		ilog "Copying $image to ${BMC_SSH_USER}@${BMC_IP}:${BMC_TMP_DIR}/golden-image-arm"
-		sshpass -p $BMC_SSH_PASSWORD $SCP $image ${BMC_SSH_USER}@${BMC_IP}:${BMC_TMP_DIR}/golden-image-arm
-		ilog "Installing DPU Golden Image on the BMC by: dpu_golden_image golden_image_arm -w ${BMC_TMP_DIR}/golden-image-arm/$(basename $image)"
-		output=$(sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} dpu_golden_image golden_image_arm -w ${BMC_TMP_DIR}/golden-image-arm/$(basename $image) 2>&1)
-		if [ $? -eq 0 ]; then
-			log "DPU Golden Image installed successfully"
-		else
-			log "DPU Golden Image installed failed"
-			rc=1
-		fi
-		ilog "$output"
+		image_type="bfb"
 	fi
+
+	if [ "$image_type" == "bfb" ]; then
+		prepare_sshpass_environment
+
+		ilog "Found DPU Golden Image: $image"
+		DPU_GI_IMAGE_VERSION="$(sha256sum $image | awk '{print $1}')"
+		ilog "Provided DPU Golden Image version: $DPU_GI_IMAGE_VERSION"
+
+		DPU_GI_INSTALLED_VERSION="$(sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} dpu_golden_image golden_image_arm -V 2> /dev/null)"
+		ilog "Installed DPU Golden Image version: $DPU_GI_INSTALLED_VERSION"
+
+		if [ "$DPU_GI_IMAGE_VERSION" == "$DPU_GI_INSTALLED_VERSION" ]; then
+			ilog "Installed DPU Golden Image version is the same as provided. Skipping DPU Golden Image update."
+		else
+			sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} mkdir -p ${BMC_TMP_DIR}/golden-image-arm
+			ilog "Copying $image to ${BMC_SSH_USER}@${BMC_IP}:${BMC_TMP_DIR}/golden-image-arm"
+			sshpass -p $BMC_SSH_PASSWORD $SCP $image ${BMC_SSH_USER}@${BMC_IP}:${BMC_TMP_DIR}/golden-image-arm
+			ilog "Installing DPU Golden Image on the BMC by: dpu_golden_image golden_image_arm -w ${BMC_TMP_DIR}/golden-image-arm/$(basename $image)"
+			output=$(sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} dpu_golden_image golden_image_arm -w ${BMC_TMP_DIR}/golden-image-arm/$(basename $image) 2>&1)
+			if [ $? -eq 0 ]; then
+				log "DPU Golden Image installed successfully"
+			else
+				log "DPU Golden Image installed failed"
+				rc=1
+			fi
+			ilog "$output"
+		fi
+
+		if (echo "${BD_PSIDS}" | grep -qw "${PSID}"); then
+			if [ "X${UPLOAD_CONFIG_IMAGE}" == "Xyes" ]; then
+				if [ "X${GENERATE_CONFIG_IMAGE}" == "Xyes" ]; then
+					generate_config_image $image
+				fi
+				config_image=${DPU_GI_PATH}/${CONFIG_IMAGE}
+				if [ ! -e "$config_image" ]; then
+					ilog "Config image does not exist: $config_image"
+					return 1
+				fi
+				sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} mkdir -p ${BMC_TMP_DIR}/golden-image-config
+				ilog "Copying $config_image to ${BMC_SSH_USER}@${BMC_IP}:${BMC_TMP_DIR}/golden-image-config"
+				sshpass -p $BMC_SSH_PASSWORD $SCP $config_image ${BMC_SSH_USER}@${BMC_IP}:${BMC_TMP_DIR}/golden-image-config
+				if [ "X$BMC_INSTALL_CONFIG_IMAGE" == "Xyes" ]; then
+					ilog "Installing DPU Config Image on the BMC by: dpu_golden_image golden_image_config -w ${BMC_TMP_DIR}/golden-image-config/$(basename $config_image)"
+					output=$(sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} dpu_golden_image golden_image_config -w ${BMC_TMP_DIR}/golden-image-config/$(basename $config_image) 2>&1)
+					if [ $? -eq 0 ]; then
+						log "Installed BMC config image"
+						BMC_CONFIG_UPDATED="yes"
+					else
+						log "Failed to install BMC config image"
+					fi
+					ilog "$output"
+				fi
+			fi
+		fi
+	elif [ "$image_type" == "pldm" ]; then
+		if [ -z "$BMC_INSTALLED_VERSION" ]; then
+			get_bmc_firmware_version
+		fi
+
+		if [[ $(echo -e "${BMC_MIN_MULTIPART_VERSION_PLDM}\n${BMC_INSTALLED_VERSION}" | sort -V | head -n1) == "${BMC_MIN_MULTIPART_VERSION_PLDM}" ]]; then
+			ilog "curl -k -H \"X-Auth-Token: <BMC_TOKEN>\" -X POST https://${BMC_IP}/redfish/v1/UpdateService/update-multipart  -F 'UpdateParameters={};type=application/json'  -F \"UpdateFile=@${image};type=application/octet-stream\""
+			output=$(curl -sSk -H "X-Auth-Token: $BMC_TOKEN" -X POST https://${BMC_IP}/redfish/v1/UpdateService/update-multipart  -F 'UpdateParameters={};type=application/json'  -F "UpdateFile=@${image};type=application/octet-stream" 2>&1)
+			ilog "BMC Firmware update: $output"
+		else
+			ilog "DPU Golden Image update is not supported for BMC firmware version $BMC_INSTALLED_VERSION"
+			ilog "Please update BMC firmware to version $BMC_MIN_MULTIPART_VERSION_PLDM or higher"
+			RC=$((RC+1))
+			return 1
+		fi
+	fi
+	return $rc
 }
 
 update_nic_firmware_golden_image()
 {
 	rc=0
 	log "Updating NIC firmware Golden Image"
+	image_type=""
 	image=${NIC_FW_GOLDEN_IMAGE}
 
 	if [ -z "$image" ]; then
@@ -589,30 +653,53 @@ update_nic_firmware_golden_image()
 		return 1
 	fi
 
-	prepare_sshpass_environment
-
-	ilog "Found NIC firmware Golden Image: $image"
-	NIC_GI_IMAGE_VERSION="$(sha256sum $image | awk '{print $1}')"
-	ilog "Provided NIC firmware Golden Image version: $NIC_GI_IMAGE_VERSION"
-
-	NIC_GI_INSTALLED_VERSION="$(sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} dpu_golden_image golden_image_nic -V 2> /dev/null)"
-	ilog "Installed NIC firmware Golden Image version: $NIC_GI_INSTALLED_VERSION"
-
-	if [ "$NIC_GI_IMAGE_VERSION" == "$NIC_GI_INSTALLED_VERSION" ]; then
-		ilog "Installed NIC firmware Golden Image version is the same as provided. Skipping NIC firmware Golden Image update."
-		return 0
-	fi
-
-	sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} mkdir -p ${BMC_TMP_DIR}/golden-image-nic
-	sshpass -p $BMC_SSH_PASSWORD $SCP $image ${BMC_SSH_USER}@${BMC_IP}:${BMC_TMP_DIR}/golden-image-nic
-	output=$(sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} dpu_golden_image golden_image_nic -w ${BMC_TMP_DIR}/golden-image-nic/$(basename $image) 2>&1)
-	if [ $? -eq 0 ]; then
-		log "NIC firmware Golden Image installed successfully"
+	if is_pldm_file $image; then
+		image_type="pldm"
 	else
-		log "NIC firmware Golden Image installed failed"
-		rc=1
+		image_type="bfb"
 	fi
-	ilog "$output"
+
+	if [ "$image_type" == "bfb" ]; then
+		prepare_sshpass_environment
+
+		ilog "Found NIC firmware Golden Image: $image"
+		NIC_GI_IMAGE_VERSION="$(sha256sum $image | awk '{print $1}')"
+		ilog "Provided NIC firmware Golden Image version: $NIC_GI_IMAGE_VERSION"
+
+		NIC_GI_INSTALLED_VERSION="$(sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} dpu_golden_image golden_image_nic -V 2> /dev/null)"
+		ilog "Installed NIC firmware Golden Image version: $NIC_GI_INSTALLED_VERSION"
+
+		if [ "$NIC_GI_IMAGE_VERSION" == "$NIC_GI_INSTALLED_VERSION" ]; then
+			ilog "Installed NIC firmware Golden Image version is the same as provided. Skipping NIC firmware Golden Image update."
+			return 0
+		fi
+
+		sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} mkdir -p ${BMC_TMP_DIR}/golden-image-nic
+		sshpass -p $BMC_SSH_PASSWORD $SCP $image ${BMC_SSH_USER}@${BMC_IP}:${BMC_TMP_DIR}/golden-image-nic
+		output=$(sshpass -p $BMC_SSH_PASSWORD $SSH ${BMC_SSH_USER}@${BMC_IP} dpu_golden_image golden_image_nic -w ${BMC_TMP_DIR}/golden-image-nic/$(basename $image) 2>&1)
+		if [ $? -eq 0 ]; then
+			log "NIC firmware Golden Image installed successfully"
+		else
+			log "NIC firmware Golden Image installed failed"
+			rc=1
+		fi
+		ilog "$output"
+	elif [ "$image_type" == "pldm" ]; then
+		if [ -z "$BMC_INSTALLED_VERSION" ]; then
+			get_bmc_firmware_version
+		fi
+
+		if [[ $(echo -e "${BMC_MIN_MULTIPART_VERSION_PLDM}\n${BMC_INSTALLED_VERSION}" | sort -V | head -n1) == "${BMC_MIN_MULTIPART_VERSION_PLDM}" ]]; then
+			ilog "curl -k -H \"X-Auth-Token: <BMC_TOKEN>\" -X POST https://${BMC_IP}/redfish/v1/UpdateService/update-multipart  -F 'UpdateParameters={};type=application/json'  -F \"UpdateFile=@${image};type=application/octet-stream\""
+			output=$(curl -sSk -H "X-Auth-Token: $BMC_TOKEN" -X POST https://${BMC_IP}/redfish/v1/UpdateService/update-multipart  -F 'UpdateParameters={};type=application/json'  -F "UpdateFile=@${image};type=application/octet-stream" 2>&1)
+			ilog "BMC Firmware update: $output"
+		else
+			ilog "NIC Firmware Golden Image update is not supported for BMC firmware version $BMC_INSTALLED_VERSION"
+			ilog "Please update BMC firmware to version $BMC_MIN_MULTIPART_VERSION_PLDM or higher"
+			RC=$((RC+1))
+			return 1
+		fi
+	fi
 	return $rc
 }
 
