Added BFB components installation progress
The installation progress will appear on the DPU console and in the log
file.

Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/src/bf-upgrade b/src/bf-upgrade
--- a/src/bf-upgrade
+++ b/src/bf-upgrade
@@ -106,15 +106,19 @@ fi
 
 if [ "$UPDATE_ATF_UEFI" == "yes" ]; then
 	if [ -e dump-capsule-v0 ]; then
-		if function_exists update_atf_uefi; then
-			update_atf_uefi $(readlink -f dump-capsule-v0)
-		else
+		if ! function_exists update_atf_uefi; then
 			log  "ERROR: BSP upgrade function does not exist"
+			UPDATE_ATF_UEFI="no"
 		fi
 	else
 		log "ERROR: BSP upgrade capsule dump-capsule-v0 was not found"
 		UPDATE_ATF_UEFI="no"
 	fi
+fi
+
+if ! function_exists bmc_components_update; then
+	log  "ERROR: BMC upgrade function does not exist"
+	skip_bmc 0
 fi
 
 if [ "$UPDATE_BMC_FW" == "yes" ]; then
@@ -135,6 +139,8 @@ if [ "$UPDATE_CEC_FW" == "yes" ]; then
 	fi
 fi
 
+UPDATE_DPU_GOLDEN_IMAGE="no"
+
 if [ "$UPDATE_NIC_FW_GOLDEN_IMAGE" == "yes" ]; then
 	if [ -e dump-ramdisk-v0 ]; then
 		NIC_FW_GOLDEN_IMAGE=$(readlink -f dump-ramdisk-v0)
@@ -144,24 +150,34 @@ if [ "$UPDATE_NIC_FW_GOLDEN_IMAGE" == "yes" ]; then
 	fi
 fi
 
-if function_exists update_atf_uefi; then
-	bmc_components_update
-else
-	log  "ERROR: BMC upgrade function does not exist"
-fi
-
 if [ "$WITH_NIC_FW_UPDATE" == "yes" ]; then
 	if [ -e dump-nicfw-v0 ]; then
 		if function_exists update_nic_firmware; then
 			NIC_FW_BIN=$(readlink -f dump-nicfw-v0)
-			update_nic_firmware
 		else
 			log  "ERROR: NIC Firmware upgrade function does not exist"
+			WITH_NIC_FW_UPDATE="no"
 		fi
 	else
 		# log "ERROR: NIC firmware binary dump-nicfw-v0 was not found"
 		WITH_NIC_FW_UPDATE="no"
 	fi
+fi
+
+calculate_total_weight
+update_progress install_setup 0
+
+# Update components
+if [ "$UPDATE_ATF_UEFI" == "yes" ]; then
+	update_atf_uefi $(readlink -f dump-capsule-v0)
+	update_progress atf_uefi $?
+fi
+
+bmc_components_update
+
+if [ "$WITH_NIC_FW_UPDATE" == "yes" ]; then
+	update_nic_firmware
+	update_progress nic_firmware $?
 fi
 
 cd ${WDIR}
diff --git a/src/dpu-bmc-upgrade b/src/dpu-bmc-upgrade
--- a/src/dpu-bmc-upgrade
+++ b/src/dpu-bmc-upgrade
@@ -101,15 +101,19 @@ fi
 
 if [ "$UPDATE_ATF_UEFI" == "yes" ]; then
 	if [ -e "${ATF_UEFI_IMAGE}" ]; then
-		if function_exists update_atf_uefi; then
-			update_atf_uefi "${ATF_UEFI_IMAGE}"
-		else
+		if ! function_exists update_atf_uefi; then
 			log  "ERROR: BSP upgrade function does not exist"
+			UPDATE_ATF_UEFI="no"
 		fi
 	else
 		log "ERROR: BSP upgrade capsule ${ATF_UEFI_IMAGE} was not found"
 		UPDATE_ATF_UEFI="no"
 	fi
+fi
+
+if ! function_exists bmc_components_update; then
+	log  "ERROR: BMC upgrade function does not exist"
+	skip_bmc 0
 fi
 
 if [ "$UPDATE_BMC_FW" == "yes" ]; then
@@ -133,11 +137,16 @@ if [ "$UPDATE_NIC_FW_GOLDEN_IMAGE" == "yes" ]; then
 	fi
 fi
 
-if function_exists update_atf_uefi; then
-	bmc_components_update
-else
-	log  "ERROR: BMC upgrade function does not exist"
+calculate_total_weight
+update_progress install_setup 0
+
+# Update components
+if [ "$UPDATE_ATF_UEFI" == "yes" ]; then
+	update_atf_uefi "${ATF_UEFI_IMAGE}"
+	update_progress atf_uefi $?
 fi
+
+bmc_components_update
 
 log "Runtime upgrade finished"
 sleep 3
