src/dpu-bmc-upgrade: Support NIC FW upgrade
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/src/dpu-bmc-upgrade b/src/dpu-bmc-upgrade
--- a/src/dpu-bmc-upgrade
+++ b/src/dpu-bmc-upgrade
@@ -148,5 +148,16 @@ fi
 
 bmc_components_update
 
+if [ "$WITH_NIC_FW_UPDATE" == "yes" ]; then
+	if function_exists update_nic_firmware; then
+		MLXFWRESET_TIMEOUT=${MLXFWRESET_TIMEOUT:-0}
+		update_nic_firmware
+		update_progress nic_firmware $?
+		reset_nic_firmware
+	else
+		log  "ERROR: NIC FW upgrade function does not exist"
+	fi
+fi
+
 log "Runtime upgrade finished"
 sleep 3
